feat: Added functionality for creating new streams and consumers in nats
unbxd/go-base pull request #41
Opened 2022-06-14 08:49 UTC by akshedu

2022-06-18 07:11 UTC, uknth commented
Right of the bat, without even reading your code. 
1. `feat: <information>` if you are writing new feature, feat is enough, you don't need to explain "added functionality", you could have written `feat: creates new stream and consumers in nats`
2. Commit messages are imperative, which basically means you are giving an instruction. So, instead of `Added` use verbs like `adds` etc.

2022-06-18 07:22 UTC, uknth requested changes
The way I understood what you are doing here is, you will do something like this in your application
```
si, err := stream.GetInfo()
// check err

si.SomeMethod() // where some method is exposed by the NATS library
```
If this is the case, your implementation isn't correct. You are leaking information. Understand this, the whole idea of this project is to have `endpoint.Endpoint` be central exposed method. This is to ensure that we can change the implementation from NATS to HTTP or KAFKA very easily. 

This current implementation isn't really a library, it is more like you directly using NATS in your application, just your code is residing here.

2022-06-18 07:22 UTC, uknth commented on kit/transport/nats/consumer.go
> +func (c *Consumer) GetConsumerInfo() (*natn.ConsumerInfo, error) {
Can you use an internal object to `go-base` as output of this method? This leaks the internal details which will then require the upstream to import nats dependency.

2022-06-18 07:22 UTC, uknth commented on kit/transport/nats/consumer.go
> +func NewConsumer(connstr string, stream string, options ...ConsumerOption) (*Consumer, error) {
Can you keep this in line with rest of the NATS implementation?
Either change NATS to call it Consumer everywhere, i.e. existing implementation as well or change this to `NewStreamSubscriber()`

2022-06-18 07:22 UTC, uknth commented on kit/transport/nats/consumer.go
> +	js, _ := cc.JetStream()
If the second variable returned is an error, handle it.

2022-07-26 09:50 UTC, keshareenv commented
@uknth @akshedu Can we take this forward please, rn we are using the fork for deadpool initial release

2022-07-26 09:56 UTC, akshedu commented
@uknth let me know if any changes are required as per the latest implementation. After our discussion I had incorporated everything

2023-12-11 09:37 UTC, closed without merging